spring:
  config:
    import: optional:file:.env[.properties]
  mail:
    host: ${MAIL_HOST}
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
  cloud:
    aws:
      sqs:
        region: us-east-1
        endpoint: ${SQS_ENDPOINT}
server:
  port: 8081
aws:
  sqs:
    region: us-east-1
    endpoint: ${SQS_ENDPOINT}