spring:
  redis:
    topic: ${TOPIC_NAME}
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: true
  config:
    import: optional:file:.env[.properties]
  mail:
    host: ${MAIL_HOST}
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
  cloud:
    aws:
      sns:
        region: ${AWS_REGION}
      sqs:
        name: ${TOPIC_NAME}
        arn: ${SNS_TOPIC_ARN}
        region: ${AWS_REGION}
server:
  port: 8081